# ============================================================
# SHADOWFORGE OS — GITHUB ACTIONS WORKFLOW GENERATOR
# Generates .github/workflows/*.yml files for multi-platform
# builds: Windows EXE, macOS DMG, Linux AppImage, Android APK.
# Also generates web deploy, test, and release workflows.
# ============================================================

import re
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime

from core.logger import get_logger
from core.constants import APP_NAME, APP_VERSION

logger = get_logger("GitHub.WorkflowGen")


# ── BUILD TARGET ──────────────────────────────────────────
@dataclass
class BuildTarget:
    platform:    str
    os:          str         # GitHub runner OS
    arch:        str
    output_ext:  str
    output_name: str
    extra_steps: List[str] = field(default_factory=list)
    env_vars:    Dict[str, str] = field(default_factory=dict)


STANDARD_TARGETS = {
    "windows": BuildTarget(
        platform    = "windows",
        os          = "windows-latest",
        arch        = "x64",
        output_ext  = ".exe",
        output_name = "{app_name}-Setup-Windows.exe",
    ),
    "macos": BuildTarget(
        platform    = "macos",
        os          = "macos-latest",
        arch        = "x64",
        output_ext  = ".dmg",
        output_name = "{app_name}-macOS.dmg",
        extra_steps = [
            "brew install create-dmg",
        ],
    ),
    "linux": BuildTarget(
        platform    = "linux",
        os          = "ubuntu-latest",
        arch        = "x86_64",
        output_ext  = ".AppImage",
        output_name = "{app_name}-Linux.AppImage",
        extra_steps = [
            "sudo apt-get update -qq",
            "sudo apt-get install -y libfuse2 portaudio19-dev libgl1",
        ],
    ),
    "android": BuildTarget(
        platform    = "android",
        os          = "ubuntu-latest",
        arch        = "arm64",
        output_ext  = ".apk",
        output_name = "{app_name}-Android.apk",
        extra_steps = [
            "sudo apt-get update -qq",
            "sudo apt-get install -y openjdk-17-jdk",
            "pip install buildozer cython",
        ],
    ),
}


# ── WORKFLOW GENERATOR ────────────────────────────────────
class WorkflowGenerator:
    """
    Generates GitHub Actions YAML workflow files.

    Supports:
    - Multi-platform desktop builds (Windows/macOS/Linux)
    - Android APK build
    - Web deployment (Render, Vercel, Netlify)
    - Test & lint CI
    - Auto-release on tag push
    - Landing page deployment
    """

    def __init__(self, app_name: str, app_version: str = "1.0.0"):
        self.app_name    = re.sub(r'[^\w\-]', '-', app_name.strip())
        self.app_version = app_version
        logger.info(
            f"WorkflowGenerator initialized: {self.app_name} v{self.app_version}"
        )

    # ── MULTI-PLATFORM BUILD WORKFLOW ─────────────────────
    def generate_build_workflow(
        self,
        platforms:      Optional[List[str]] = None,
        python_version: str = "3.11",
        entry_script:   str = "app/core/main.py",
        icon_path:      str = "public/assets/logo.ico",
        requirements:   str = "requirements.txt",
        triggers:       Optional[List[str]] = None,
    ) -> str:
        """Generate the main multi-platform build workflow."""

        platforms = platforms or ["windows", "macos", "linux"]
        triggers  = triggers  or ["push:tags:v*", "workflow_dispatch"]

        # Build matrix
        matrix_includes = []
        for platform in platforms:
            target = STANDARD_TARGETS.get(platform)
            if not target:
                continue
            matrix_includes.append({
                "platform": platform,
                "os":       target.os,
                "arch":     target.arch,
                "output":   target.output_name.format(app_name=self.app_name),
                "ext":      target.output_ext,
            })

        matrix_json = json.dumps({"include": matrix_includes}, indent=2)

        # Per-platform install steps
        platform_install_steps = self._build_platform_install_steps()

        # Per-platform build commands
        platform_build_commands = self._build_platform_build_commands(
            entry_script, icon_path
        )

        workflow = f"""# ============================================================
# SHADOWFORGE OS — MULTI-PLATFORM BUILD WORKFLOW
# Auto-generated by ShadowForge OS v{APP_VERSION}
# Builds: {', '.join(platforms)}
# Triggers: push to tags (v*) or manual dispatch
# ============================================================

name: Build — All Platforms

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated)'
        required: false
        default: 'all'

permissions:
  contents: write
  actions: read

jobs:
  build:
    name: Build [${{{{ matrix.platform }}}}]
    runs-on: ${{{{ matrix.os }}}}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
{self._yaml_matrix(matrix_includes)}

    steps:
      # ── CHECKOUT ──────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ── PYTHON SETUP ──────────────────────────────────
      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'
          cache: 'pip'

      # ── PLATFORM DEPENDENCIES ─────────────────────────
      - name: Install system dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \\
            libfuse2 \\
            portaudio19-dev \\
            libgl1-mesa-glx \\
            libglib2.0-0 \\
            libxcb-xinerama0 \\
            libxcb-icccm4 \\
            libxcb-image0 \\
            libxcb-keysyms1 \\
            libxcb-render-util0 \\
            libxkbcommon-x11-0

      - name: Install system dependencies (macOS)
        if: matrix.platform == 'macos'
        run: |
          brew install portaudio create-dmg || true

      - name: Install system dependencies (Windows)
        if: matrix.platform == 'windows'
        run: |
          choco install portaudio --no-progress -y || true
        shell: powershell

      # ── PYTHON DEPENDENCIES ───────────────────────────
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r {requirements}
          pip install pyinstaller==6.3.0

      # ── CREATE ENV FILE ───────────────────────────────
      - name: Create .env file from secrets
        run: |
          echo "OPENROUTER_API_KEY=${{{{ secrets.OPENROUTER_API_KEY }}}}" >> app/.env
          echo "GROQ_API_KEY=${{{{ secrets.GROQ_API_KEY }}}}" >> app/.env
          echo "TOGETHER_API_KEY=${{{{ secrets.TOGETHER_API_KEY }}}}" >> app/.env
          echo "MISTRAL_API_KEY=${{{{ secrets.MISTRAL_API_KEY }}}}" >> app/.env
          echo "GOOGLE_AI_API_KEY=${{{{ secrets.GOOGLE_AI_API_KEY }}}}" >> app/.env
          echo "GITHUB_TOKEN=${{{{ secrets.FORGE_GITHUB_TOKEN }}}}" >> app/.env
          echo "GITHUB_USERNAME=${{{{ secrets.GITHUB_USERNAME }}}}" >> app/.env
          echo "DEBUG=false" >> app/.env
          echo "SANDBOX_MODE=true" >> app/.env
        shell: bash

      # ── BUILD WITH PYINSTALLER (Desktop) ──────────────
      - name: Build Desktop App (Windows/macOS/Linux)
        if: matrix.platform != 'android'
        run: |
          pyinstaller \\
            --name "{self.app_name}" \\
            --onefile \\
            --windowed \\
            --icon "{icon_path}" \\
            --add-data "app/config:config" \\
            --add-data "app/ui/styles:ui/styles" \\
            --add-data "public/assets:assets" \\
            --hidden-import PyQt6 \\
            --hidden-import PyQt6.QtCore \\
            --hidden-import PyQt6.QtWidgets \\
            --hidden-import PyQt6.QtGui \\
            --hidden-import speech_recognition \\
            --hidden-import groq \\
            --hidden-import openai \\
            --clean \\
            --noconfirm \\
            {entry_script}
        shell: bash

      # ── PACKAGE WINDOWS EXE ───────────────────────────
      - name: Package Windows installer
        if: matrix.platform == 'windows'
        run: |
          $source = "dist\\{self.app_name}.exe"
          $dest   = "dist\\{self.app_name}-Setup-Windows.exe"
          if (Test-Path $source) {{
            Copy-Item $source $dest
            Write-Host "Packaged: $dest"
          }} else {{
            Write-Error "Build output not found: $source"
            exit 1
          }}
        shell: powershell

      # ── PACKAGE MACOS DMG ─────────────────────────────
      - name: Package macOS DMG
        if: matrix.platform == 'macos'
        run: |
          if [ -d "dist/{self.app_name}.app" ]; then
            create-dmg \\
              --volname "{self.app_name}" \\
              --window-pos 200 120 \\
              --window-size 600 400 \\
              --icon-size 100 \\
              --app-drop-link 425 130 \\
              "dist/{self.app_name}-macOS.dmg" \\
              "dist/{self.app_name}.app"
          elif [ -f "dist/{self.app_name}" ]; then
            cp "dist/{self.app_name}" "dist/{self.app_name}-macOS.dmg"
          fi

      # ── PACKAGE LINUX APPIMAGE ─────────────────────────
      - name: Package Linux AppImage
        if: matrix.platform == 'linux'
        run: |
          if [ -f "dist/{self.app_name}" ]; then
            cp "dist/{self.app_name}" "dist/{self.app_name}-Linux.AppImage"
            chmod +x "dist/{self.app_name}-Linux.AppImage"
          fi

      # ── BUILD ANDROID APK ─────────────────────────────
      - name: Build Android APK
        if: matrix.platform == 'android'
        run: |
          pip install buildozer cython
          cd app
          buildozer android debug 2>&1 | tail -50
          find . -name "*.apk" -exec cp {{}} "../dist/{self.app_name}-Android.apk" \\;
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      # ── VERIFY BUILD OUTPUT ───────────────────────────
      - name: Verify build output
        run: |
          ls -la dist/ || dir dist\\
        shell: bash

      # ── UPLOAD ARTIFACT ───────────────────────────────
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{{{ matrix.platform }}}}-build
          path: dist/${{{{ matrix.output }}}}
          retention-days: 14
          if-no-files-found: warn

  # ── RELEASE JOB (runs after all builds) ───────────────
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets/

      - name: List downloaded assets
        run: find release-assets/ -type f | sort

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${{{{ github.ref_name }}}}
          cat > release_notes.md << EOF
          # ${{{{ github.repository_name }}}} $VERSION

          **Built by ShadowForge OS** — AI-powered project generator.

          ## Downloads

          | Platform | File |
          |----------|------|
          | 🪟 Windows | \`{self.app_name}-Setup-Windows.exe\` |
          | 🍎 macOS | \`{self.app_name}-macOS.dmg\` |
          | 🐧 Linux | \`{self.app_name}-Linux.AppImage\` |
          | 📱 Android | \`{self.app_name}-Android.apk\` |

          ## Installation
          - **Windows**: Run the `.exe` installer
          - **macOS**: Mount the `.dmg` and drag to Applications
          - **Linux**: \`chmod +x *.AppImage && ./*.AppImage\`
          - **Android**: Enable "Install from unknown sources" and install APK

          ## API Keys Required
          Add your API keys to the app settings after first launch.
          At least one provider key is needed (Groq is free and recommended).

          ---
          *Generated: $(date -u)*
          EOF
          echo "notes_file=release_notes.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "{self.app_name} ${{{{ github.ref_name }}}}"
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            release-assets/**/*
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Comment release URL
        run: |
          echo "Release published!"
          echo "URL: https://github.com/${{{{ github.repository }}}}/releases/tag/${{{{ github.ref_name }}}}"
"""
        return workflow

    # ── CI/TEST WORKFLOW ──────────────────────────────────
    def generate_ci_workflow(
        self,
        python_versions: Optional[List[str]] = None,
        requirements:    str = "requirements.txt",
    ) -> str:
        """Generate CI workflow for testing."""
        python_versions = python_versions or ["3.10", "3.11", "3.12"]

        return f"""# ============================================================
# SHADOWFORGE OS — CI / TEST WORKFLOW
# Runs on every push and PR to main branch
# ============================================================

name: CI — Test & Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{{{ matrix.python-version }}}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: {json.dumps(python_versions)}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{{{ matrix.python-version }}}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ matrix.python-version }}}}
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y portaudio19-dev libgl1 -qq

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r {requirements}
          pip install pytest pytest-cov black mypy

      - name: Create test .env
        run: |
          echo "GROQ_API_KEY=test_key" >> app/.env
          echo "DEBUG=true" >> app/.env
          echo "SANDBOX_MODE=true" >> app/.env

      - name: Run tests
        run: |
          python -m pytest app/tests/ \\
            --cov=app \\
            --cov-report=xml \\
            --cov-report=term-missing \\
            -v \\
            --tb=short
        env:
          PYTHONPATH: .

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          fail_ci_if_error: false

      - name: Lint with black
        run: |
          black --check app/ --line-length 100 || true

      - name: Type check with mypy
        run: |
          mypy app/core/ --ignore-missing-imports --no-strict-optional || true
"""

    # ── LANDING PAGE DEPLOY WORKFLOW ──────────────────────
    def generate_landing_deploy_workflow(
        self,
        deploy_target: str = "github-pages",
    ) -> str:
        """Generate workflow to deploy landing page."""

        if deploy_target == "github-pages":
            return f"""# ============================================================
# SHADOWFORGE OS — LANDING PAGE DEPLOY (GitHub Pages)
# ============================================================

name: Deploy — Landing Page

on:
  push:
    branches: [ main ]
    paths:
      - 'landing/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload landing directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: landing/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output URL
        run: |
          echo "Landing deployed to: ${{{{ steps.deployment.outputs.page_url }}}}"
"""
        else:
            return f"""# Deploy to Render (configure in render.yaml)
name: Deploy — Landing (Render)
on:
  push:
    branches: [ main ]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Render auto-deploys on push to main."
"""

    # ── RELEASE TAG WORKFLOW ──────────────────────────────
    def generate_auto_tag_workflow(self) -> str:
        """Generate workflow that auto-tags on version bump."""
        return f"""# ============================================================
# SHADOWFORGE OS — AUTO TAG ON VERSION BUMP
# Reads version from app/core/constants.py and creates tag
# ============================================================

name: Auto Tag Release

on:
  push:
    branches: [ main ]
    paths:
      - 'app/core/constants.py'

permissions:
  contents: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Extract version
        id: version
        run: |
          VERSION=$(python -c "
          import re, sys
          sys.path.insert(0, '.')
          content = open('app/core/constants.py').read()
          match = re.search(r'APP_VERSION\\s*=\\s*[\"\\']([^\"\\']+)[\"\\']', content)
          print(match.group(1) if match else '0.0.0')
          ")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: v$VERSION"

      - name: Check if tag exists
        id: tag_check
        run: |
          if git rev-parse "${{{{ steps.version.outputs.version }}}}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name  "ShadowForge Bot"
          git config user.email "bot@shadowforge.dev"
          git tag -a "${{{{ steps.version.outputs.version }}}}" \\
            -m "Release ${{{{ steps.version.outputs.version }}}}"
          git push origin "${{{{ steps.version.outputs.version }}}}"
          echo "Tag created: ${{{{ steps.version.outputs.version }}}}"
"""

    # ── HELPERS ───────────────────────────────────────────
    def _yaml_matrix(self, includes: List[Dict]) -> str:
        """Format matrix includes as YAML."""
        lines = []
        for item in includes:
            lines.append(f"          - platform: {item['platform']}")
            lines.append(f"            os: {item['os']}")
            lines.append(f"            arch: {item['arch']}")
            lines.append(f"            output: \"{item['output']}\"")
            lines.append(f"            ext: {item['ext']}")
        return "\n".join(lines)

    def _build_platform_install_steps(self) -> str:
        return ""  # Inlined in workflow above

    def _build_platform_build_commands(
        self, entry_script: str, icon_path: str
    ) -> str:
        return ""  # Inlined in workflow above

    # ── WRITE ALL WORKFLOWS ───────────────────────────────
    def write_all_workflows(
        self,
        output_dir: Path,
        platforms:  Optional[List[str]] = None,
    ) -> Dict[str, bool]:
        """Write all workflow files to .github/workflows/."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        results: Dict[str, bool] = {}

        workflows = {
            "build-all-platforms.yml": self.generate_build_workflow(platforms),
            "ci-test.yml":             self.generate_ci_workflow(),
            "deploy-landing.yml":      self.generate_landing_deploy_workflow(),
            "auto-tag.yml":            self.generate_auto_tag_workflow(),
        }

        for filename, content in workflows.items():
            filepath = output_dir / filename
            try:
                with open(filepath, "w", encoding="utf-8", newline="\n") as f:
                    f.write(content)
                results[filename] = True
                logger.info(f"Workflow written: {filename}")
            except Exception as e:
                logger.error(f"Failed to write {filename}: {e}")
                results[filename] = False

        return results